# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\dashboard_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DashboardWindow(object):
    def setupUi(self, DashboardWindow):
        DashboardWindow.setObjectName("DashboardWindow")
        DashboardWindow.resize(805, 612)
        self.centralwidget = QtWidgets.QWidget(DashboardWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.dashTable = QtWidgets.QTabWidget(self.centralwidget)
        self.dashTable.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dashTable.setObjectName("dashTable")
        self.todatTab = QtWidgets.QWidget()
        self.todatTab.setObjectName("todatTab")
        self.dashTable.addTab(self.todatTab, "")
        self.statisticsTab = QtWidgets.QWidget()
        self.statisticsTab.setObjectName("statisticsTab")
        self.dashTable.addTab(self.statisticsTab, "")
        self.sensorsTab = QtWidgets.QWidget()
        self.sensorsTab.setObjectName("sensorsTab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.sensorsTab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.snsr_edit_widget = SnsrEditWidget(self.sensorsTab)
        self.snsr_edit_widget.setObjectName("snsr_edit_widget")
        self.verticalLayout_2.addWidget(self.snsr_edit_widget)
        self.dashTable.addTab(self.sensorsTab, "")
        self.verticalLayout.addWidget(self.dashTable)
        DashboardWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(DashboardWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 805, 21))
        self.menubar.setObjectName("menubar")
        DashboardWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(DashboardWindow)
        self.statusbar.setObjectName("statusbar")
        DashboardWindow.setStatusBar(self.statusbar)

        self.retranslateUi(DashboardWindow)
        self.dashTable.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DashboardWindow)

    def retranslateUi(self, DashboardWindow):
        _translate = QtCore.QCoreApplication.translate
        DashboardWindow.setWindowTitle(_translate("DashboardWindow", "MainWindow"))
        self.label.setText(_translate("DashboardWindow", "Dashboard"))
        self.dashTable.setTabText(self.dashTable.indexOf(self.todatTab), _translate("DashboardWindow", "Today"))
        self.dashTable.setTabText(self.dashTable.indexOf(self.statisticsTab), _translate("DashboardWindow", "Statistics"))
        self.dashTable.setTabText(self.dashTable.indexOf(self.sensorsTab), _translate("DashboardWindow", "Sensors"))
from snsr_edit_widget import SnsrEditWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DashboardWindow = QtWidgets.QMainWindow()
    ui = Ui_DashboardWindow()
    ui.setupUi(DashboardWindow)
    DashboardWindow.show()
    sys.exit(app.exec_())
