# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\snsr_activ_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SnsrActvWidget(object):
    def setupUi(self, SnsrActvWidget):
        SnsrActvWidget.setObjectName("SnsrActvWidget")
        SnsrActvWidget.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(SnsrActvWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout.addLayout(self.verticalLayout_2)

        self.retranslateUi(SnsrActvWidget)
        QtCore.QMetaObject.connectSlotsByName(SnsrActvWidget)

    def retranslateUi(self, SnsrActvWidget):
        _translate = QtCore.QCoreApplication.translate
        SnsrActvWidget.setWindowTitle(_translate("SnsrActvWidget", "Form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SnsrActvWidget = QtWidgets.QWidget()
    ui = Ui_SnsrActvWidget()
    ui.setupUi(SnsrActvWidget)
    SnsrActvWidget.show()
    sys.exit(app.exec_())
