# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\snsr_edit_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SnsrEditWidget(object):
    def setupUi(self, SnsrEditWidget):
        SnsrEditWidget.setObjectName("SnsrEditWidget")
        SnsrEditWidget.resize(607, 487)
        self.verticalLayout = QtWidgets.QVBoxLayout(SnsrEditWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEdit = QtWidgets.QLineEdit(SnsrEditWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_3.addWidget(self.lineEdit)
        self.pushButton_3 = QtWidgets.QPushButton(SnsrEditWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_3.addWidget(self.pushButton_3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.pushButton_4 = QtWidgets.QPushButton(SnsrEditWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_4.addWidget(self.pushButton_4)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.snsrTableView = QtWidgets.QTableView(SnsrEditWidget)
        self.snsrTableView.setObjectName("snsrTableView")
        self.verticalLayout.addWidget(self.snsrTableView)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(SnsrEditWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(SnsrEditWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(SnsrEditWidget)
        QtCore.QMetaObject.connectSlotsByName(SnsrEditWidget)

    def retranslateUi(self, SnsrEditWidget):
        _translate = QtCore.QCoreApplication.translate
        SnsrEditWidget.setWindowTitle(_translate("SnsrEditWidget", "Form"))
        self.pushButton_3.setText(_translate("SnsrEditWidget", "Find"))
        self.pushButton_4.setText(_translate("SnsrEditWidget", "Refresh"))
        self.pushButton_2.setText(_translate("SnsrEditWidget", "Remove Sensor"))
        self.pushButton.setText(_translate("SnsrEditWidget", "Add Sensor"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SnsrEditWidget = QtWidgets.QWidget()
    ui = Ui_SnsrEditWidget()
    ui.setupUi(SnsrEditWidget)
    SnsrEditWidget.show()
    sys.exit(app.exec_())
